# escape=`

# Build executable
FROM golang:1.19 AS builder
WORKDIR /app
COPY go.mod ./
COPY go.sum ./
COPY *.go ./
ENV CGO_ENABLED=0
RUN go build -v -a -tags netgo -o release/windows/amd64/drone-s3-cache.exe .

# Runner image
FROM plugins/base:windows-1809-amd64

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone S3 Cache" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

COPY --from=builder /app/release/windows/amd64/drone-s3-cache.exe C:/bin/drone-s3-cache.exe
ENTRYPOINT [ "C:\\bin\\drone-s3-cache.exe" ]
